GET http://localhost:3001/expenses/get/yearly/2023/08
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJtYWhpa2FAZ21haWwuY29tIiwiaWF0IjoxNjkzMDQ4NDMzLCJleHAiOjE2OTMxMzQ4MzN9.JWPk4Zy4vDWxPzYDB_6Ae4XELBa1i1IbOUByAqwvgUY

